overblog_graphql:
    definitions:
        schema:
            default:
                query: Query
                mutation: Mutation
        mappings:
            auto_discover:
                bundles: false
                root_dir: false
                built_in: true
            types:
                - type: yaml
                  dir: '%kernel.project_dir%/config/graphql/types'
                  suffix: .types
