Mutation:
    type: object
    config:
        description: "Root mutation"
        fields:
            createTask:
                type: "Boolean!"
                args:
                    title: "String!"
                    description: "String!"
                    assignedUserId: "ID!"
                resolve: '@=service("App\\UI\\GraphQL\\Resolver\\TaskMutationResolver").createTask(args)'

            changeTaskStatus:
                type: "Boolean!"
                args:
                    taskId: "ID!"
                    toStatus: "TaskStatus!"
                resolve: '@=service("App\\UI\\GraphQL\\Resolver\\TaskMutationResolver").changeStatus(args)'
