Query:
    type: object
    config:
        fields:
            myTasks:
                type: "[Task!]!"
                resolve: '@=service("App\\UI\\GraphQL\\Resolver\\TaskQueryResolver").myTasks()'

            allTasks:
                type: "[Task!]!"
                resolve: '@=service("App\\UI\\GraphQL\\Resolver\\TaskQueryResolver").allTasks()'

            taskHistory:
                type: "[TaskHistoryItem!]!"
                args:
                    taskId: "ID!"
                resolve: '@=service("App\\UI\\GraphQL\\Resolver\\TaskQueryResolver").taskHistory(args["taskId"])'
